### ISSUE TITLE
✘ Container template-iot-api-1            Error

### ISSUE THREAD

**Issue by UJStudio** [kuzzleio/template-kuzzle-project#1]
Try get start with [template-kuzzle-project] but met the following error message, how to solve it?

[simon@test03 kuzzleiot]$ docker-compose up -d
[+] Running 5/5
 ✔ Network template-iot_default            Created                                                                                                                                                          0.3s
 ✔ Container template-iot-elasticsearch-1  Healthy                                                                                                                                                          0.0s
 ✔ Container template-iot-redis-1          Healthy                                                                                                                                                          0.0s
 ✘ Container template-iot-api-1            Error                                                                                                                                                            0.0s
 ✔ Container template-iot-web-1            Created                                                                                                                                                          0.0s
dependency failed to start: container template-iot-api-1 exited (127)
[simon@test03 kuzzleiot]$ docker logs template-iot-api-1

node_modules directory not found. Installing dependencies from...
npm WARN deprecated string-similarity@4.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated sorted-array@2.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated node-pre-gyp@0.14.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated async-cache@1.1.0: No longer maintained. Use [lru-cache](http://npm.im/lru-cache) version 7.6 or higher, and provide an asynchronous `fetchMethod` option.
npm notice
npm notice New major version of npm available! 9.8.1 -> 10.2.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.3>
npm notice Run `npm install -g npm@10.2.3` to update!
npm notice
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in: /var/npm/_logs/2023-11-11T17_56_04_694Z-debug-0.log
Starting application api...
Running npm run dev...

> template-iot-api@1.0.0 dev
> NODE_ENV=development ergol app.ts -c ergol.config.json

sh: 1: ergol: not found

**Comment by UJStudio** [comment]
this project contain private package?

**Comment by rolljee** [comment]
I'll be fixing that next week, ergol is a public package it shouldn't be an issue

**Comment by UJStudio** [comment]
Thanks, will try once got fixed.

**Comment by rolljee** [comment]
Hello @UJStudio do you use the command `npm run dev` to start your project ?
I don't have any issue when running this command nor with `docker compose up -d`

But if I do run this command `NODE_ENV=development ergol app.ts -c ergol.config.json` directly I encounter a 


```bash
NODE_ENV=development ergol app.ts -c ergol.config.json
zsh: command not found: ergol
```

You may want to do `npm install -g ergol` before running that.

**Comment by UJStudio** [comment]
I'm following this instrucion:
https://docs.kuzzle.io/iot-backend/3/getting-started/install-iot-platform/
firt step: [ocker compose up -d] but ran into the error

by the way, I tried [npm install -g ergol], but same issue. 

I'm on Centos like system [https://openanolis.cn/anolisos]

**Comment by rolljee** [comment]
You are on the wrong repository here. If you are following our iot platform documentation, you will end up in this repository https://github.com/kuzzleio/template-kiotp-project


Our IoT platform does require to be a licensed user in order to download private packages.
If you want to use this platform you can contact our sales team in order to get one. see here : https://kuzzle.io/kuzzle-iot-open-source-platform/demo-iot/
